<?php

namespace Database\Seeders;

use App\Models\Setting;
use Illuminate\Database\Seeder;

class SettingTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Setting::insert([
            [
                'key'      => 'logo',
                'neckname' => 'الشعار',
                'type'     => 'file',
                'value'    => 'setting/logo.png',
            ],
            [
                'key'      => 'footer_logo',
                'neckname' => 'الشعار السفلى',
                'type'     => 'file',
                'value'    => 'setting/footer-logo.png',
            ],
            [
                'key'      => 'favicon',
                'neckname' => 'ايقونة الموقع',
                'type'     => 'file',
                'value'    => 'setting/favicon.png',
            ],
            // [
            //     'key'      => 'about_image',
            //     'neckname' => 'صورة عن المنصة',
            //     'type'     => 'file',
            //     'value'    => 'setting/main_image.png',
            // ],
            // [
            //     'key'      => 'main_desc_ar',
            //     'neckname' => 'النص الرئيسى بالعربية',
            //     'type'     => 'textarea',
            //     'value'    => 'مرحباََ بك فى موقع حكيم ويب، جميع المعلومات التى يمكنك أن تثق بها.',
            // ],
            // [
            //     'key'      => 'main_desc_en',
            //     'neckname' => 'النص الرئيسى بالانجليزية',
            //     'type'     => 'textarea',
            //     'value'    => 'Welcome to the Hakeem Web site, all the information that you can trust.',
            // ],
            [
                'key'      => 'terms_of_use_ar',
                'neckname' => 'شروط الإستخدام بالعربية',
                'type'     => 'textarea',
                'value'    => 'في مكان واحد ، نوفر لك كل ما تحتاجه لدروسك في الثانوية والجامعة مع أفضل المعلمين. هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة',
            ],
            [
                'key'      => 'terms_of_use_en',
                'neckname' => 'شروط الإستخدام بالانجليزية',
                'type'     => 'textarea',
                'value'    => 'In one place we provide you everything you need for your high school and university lessons with the best teachers. This text is an example of text that can be replaced in the same space This text is an example of text that can be replaced in the same space',
            ],
            [
                'key'      => 'about_ar',
                'neckname' => 'من نحن بالعربية',
                'type'     => 'textarea',
                'value'    => 'في مكان واحد ، نوفر لك كل ما تحتاجه لدروسك في الثانوية والجامعة مع أفضل المعلمين. هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة',
            ],
            [
                'key'      => 'about_en',
                'neckname' => 'من نحن بالانجليزية',
                'type'     => 'textarea',
                'value'    => 'In one place we provide you everything you need for your high school and university lessons with the best teachers. This text is an example of text that can be replaced in the same space This text is an example of text that can be replaced in the same space',
            ],
            // [
            //     'key'      => 'vision_ar',
            //     'neckname' => 'الرؤية بالعربية',
            //     'type'     => 'textarea',
            //     'value'    => 'هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق.
            //     إذا كنت تحتاج إلى عدد أكبر من الفقرات يتيح لك مولد النص العربى زيادة عدد الفقرات كما تريد، النص لن يبدو مقسما ولا يحوي أخطاء لغوية، مولد النص العربى مفيد لمصممي المواقع على وجه',
            // ],
            // [
            //     'key'      => 'vision_en',
            //     'neckname' => 'الرؤية بالانجليزية',
            //     'type'     => 'textarea',
            //     'value'    => 'This text is an example of text that can be replaced in the same space. This text was generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application.
            //     If you need a larger number of paragraphs, the Arabic text generator allows you to increase the number of paragraphs as you want. The text will not appear divided and does not contain linguistic errors. The Arabic text generator is useful for web designers in particular.',
            // ],
            // [
            //     'key'      => 'msg_ar',
            //     'neckname' => 'رسالتنا بالعربية',
            //     'type'     => 'textarea',
            //     'value'    => 'هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق.
            //     إذا كنت تحتاج إلى عدد أكبر من الفقرات يتيح لك مولد النص العربى زيادة عدد الفقرات كما تريد، النص لن يبدو مقسما ولا يحوي أخطاء لغوية، مولد النص العربى مفيد لمصممي المواقع على وجه',
            // ],
            // [
            //     'key'      => 'msg_en',
            //     'neckname' => 'رسالتنا بالانجليزية',
            //     'type'     => 'textarea',
            //     'value'    => 'This text is an example of text that can be replaced in the same space. This text was generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application.
            //     If you need a larger number of paragraphs, the Arabic text generator allows you to increase the number of paragraphs as you want. The text will not appear divided and does not contain linguistic errors. The Arabic text generator is useful for web designers in particular.',
            // ],
            [
                'key'      => 'email',
                'neckname' => 'البريد الإلكترونى',
                'type'     => 'email',
                'value'    => 'hakemweb@gmail.com',
            ],
            [
                'key'      => 'phone',
                'neckname' => 'رقم الهاتف',
                'type'     => 'text',
                'value'    => '0112345678990',
            ],
            [
                'key'      => 'address',
                'neckname' => 'العنوان',
                'type'     => 'text',
                'value'    => 'الرياض، المملكة العربية السعودية',
            ],
            [
                'key'      => 'facebook',
                'neckname' => 'الفيسبوك',
                'type'     => 'url',
                'value'    => 'https://www.facebook.com/',
            ],
            [
                'key'      => 'snapchat',
                'neckname' => 'سناب شات',
                'type'     => 'url',
                'value'    => 'https://www.snapchat.com/',
            ],
            [
                'key'      => 'instagram',
                'neckname' => 'انستجرام',
                'type'     => 'url',
                'value'    => 'https://www.instagram.com/',
            ],
            [
                'key'      => 'twitter',
                'neckname' => 'تويتر',
                'type'     => 'url',
                'value'    => 'https://www.twitter.com/',
            ],

        ]);
    }
}
